Repository student-life-project/monorepo, pull requests merged in 2021-04, with the labels that each got.

#7 feact(front): added support for custom tailwind classes and svg
  .gitignore
  package.json
  packages/frontend/package.json
  packages/frontend/postcss.config.js
  packages/frontend/public/favicon.ico
  packages/frontend/public/fonts/MavenPro-ExtraBold.ttf
  packages/frontend/public/fonts/Montserrat-ExtraLight.ttf
  packages/frontend/public/fonts/Montserrat-Medium.ttf
  packages/frontend/public/logo.png
  packages/frontend/public/svg/logo.svg
  packages/frontend/src/icons/Logo.tsx
  packages/frontend/src/icons/index.tsx
  packages/frontend/src/pages/_app.tsx
  packages/frontend/src/pages/index.tsx
  packages/frontend/tailwind.config.js
  packages/frontend/tsconfig.json
  tailwind.config.js
  yarn.lock
Labels: enhancement, ready for merge

#5 feat/style inputs
  packages/frontend/.prettierrc
  packages/frontend/src/components/Accordion.tsx
  packages/frontend/src/components/Button.tsx
  packages/frontend/src/components/Checkbox.tsx
  packages/frontend/src/components/Input.tsx
  packages/frontend/src/components/Label.tsx
  packages/frontend/src/components/Radio.tsx
  packages/frontend/src/components/Select.tsx
  packages/frontend/src/components/SpanError.tsx
  packages/frontend/src/components/Switch.tsx
  packages/frontend/src/components/Textarea.tsx
  packages/frontend/src/pages/index.tsx
  packages/frontend/tailwind.config.js
Labels: ready for merge, ready for review

#9 fix(frontend): fixed footer to us the correct icon and link components
  packages/frontend/.eslintrc
  packages/frontend/src/components/Footer.tsx
Labels: enhancement, ready for review

#10 feat(frontend): custom error page
  packages/frontend/public/images/error.jpg
  packages/frontend/src/pages/_error.tsx
Labels: enhancement, wip

#11 fix(footer colors): fixed footer colors to match with the correct ones
  packages/frontend/src/components/Button.tsx
  packages/frontend/src/components/Footer.tsx
Labels: enhancement, ready for review

#12 feat(frontend): implemented navbar
  packages/frontend/.eslintrc
  packages/frontend/package.json
  packages/frontend/public/svg/Triangle.svg
  packages/frontend/src/components/Footer.tsx
  packages/frontend/src/components/common/NavBar/MobileMenu.tsx
  packages/frontend/src/components/common/NavBar/NavBar.tsx
  packages/frontend/src/components/common/SearchBar/SearchBar.tsx
  packages/frontend/src/components/common/SearchBar/SearchBarContainer.tsx
  packages/frontend/src/icons/Triangle.tsx
  packages/frontend/src/icons/index.tsx
  packages/frontend/src/pages/index.tsx
  packages/frontend/src/types/index.ts
  yarn.lock
Labels: enhancement

#13 feat(frontend): implemented login page
  packages/backend/package.json
  packages/common/.eslintrc
  packages/common/dist/index.d.ts
  packages/common/dist/index.js
  packages/common/dist/index.js.map
  packages/common/package.json
  packages/common/src/index.ts
  packages/common/src/utility/isServer.ts
  packages/frontend/.eslintrc
  packages/frontend/next.config.js
  packages/frontend/package.json
  packages/frontend/src/components/Footer.tsx
  packages/frontend/src/components/common/NavBar/MobileMenu.tsx
  packages/frontend/src/components/common/NavBar/NavBar.tsx
  packages/frontend/src/components/common/NavBar/NavBarContainer.tsx
  packages/frontend/src/components/common/NavBar/UserButton.tsx
  packages/frontend/src/components/common/NavBar/UserMenu.tsx
  packages/frontend/src/icons/AvatarCircle.tsx
  packages/frontend/src/icons/index.tsx
  packages/frontend/src/pages/_app.tsx
  packages/frontend/src/pages/exampleComponents.tsx
  packages/frontend/src/pages/index.tsx
  packages/frontend/src/pages/login.tsx
  packages/frontend/src/services/api.ts
  packages/frontend/src/store/actions/user.ts
  packages/frontend/src/store/index.ts
  packages/frontend/src/store/reducers/index.ts
  packages/frontend/src/store/reducers/user.ts
  packages/frontend/src/store/selectors/user.ts
  packages/frontend/src/store/types/user.ts
  packages/frontend/src/types/index.ts
  packages/frontend/src/utils/cookie.ts
  packages/frontend/src/utils/with-redux.tsx
  packages/frontend/src/utils/withServerSideAuth.ts
  yarn.lock
Labels: enhancement, wip
