Repository student-life-project/monorepo, pull requests merged in 2021-05, with the labels that each got.

#16 feat(frontend): implemented clamped text and info cards
  packages/frontend/package.json
  packages/frontend/src/components/common/ClampedText.tsx
  packages/frontend/src/components/faqs/InfoCard.tsx
  packages/frontend/src/components/faqs/ListQuestons.tsx
  packages/frontend/src/pages/faqs.tsx
  packages/frontend/src/types/index.ts
  yarn.lock
Labels: enhancement, wip

#17 feat/information page
  packages/frontend/package.json
  packages/frontend/public/images/instruction_footer_image.jpg
  packages/frontend/public/images/instruction_image.jpg
  packages/frontend/src/components/common/BodyContainer.tsx
  packages/frontend/src/components/common/BreadCrumbs.tsx
  packages/frontend/src/components/common/Card/VerticalCard.tsx
  packages/frontend/src/components/common/Title.tsx
  packages/frontend/src/pages/exampleComponents.tsx
  packages/frontend/src/pages/faqs.tsx
  packages/frontend/src/pages/help/information.tsx
  packages/frontend/src/pages/index.tsx
  packages/frontend/src/types/index.ts
  packages/frontend/src/types/styled-jsx.d.ts
  packages/frontend/src/utils/withServerSideAuth.ts
  packages/frontend/test/testUtils.ts
  yarn.lock
Labels: enhancement, wip

#18 feat(frontend): implemented register page
  packages/frontend/src/components/common/Anchor.tsx
  packages/frontend/src/components/common/CenteredBody.tsx
  packages/frontend/src/pages/register.tsx
  packages/frontend/src/store/actions/user.ts
  packages/frontend/src/store/reducers/user.ts
  packages/frontend/src/store/types/user.ts
  packages/frontend/src/types/index.ts
Labels: enhancement

#19 feat(frontend): implemented recover password page
  packages/frontend/src/pages/recover-password.tsx
Labels: enhancement

#20 feat(frontend): implemented reset password page
  packages/frontend/src/pages/login.tsx
  packages/frontend/src/pages/recover-password.tsx
  packages/frontend/src/pages/register.tsx
  packages/frontend/src/pages/reset-password.tsx
  packages/frontend/src/utils/redirectLoggedtoHome.ts
  packages/frontend/src/utils/redirectToPage.ts
Labels: enhancement, ready for merge, ready for review

#15 feat(backend): auth & guard
  packages/backend/.env.example
  packages/backend/package.json
  packages/backend/src/app.controller.ts
  packages/backend/src/app.module.ts
  packages/backend/src/authz/authz.module.ts
  packages/backend/src/authz/jwt.strategy.ts
  packages/backend/src/main.ts
  yarn.lock
Labels: enhancement

#21 feat(backend): create routes/controller/service CRUD for school & add…
  .husky/.gitignore
  packages/backend/dist/app.controller.js
  packages/backend/dist/app.controller.js.map
  packages/backend/dist/app.module.js
  packages/backend/dist/app.module.js.map
  packages/backend/dist/main.js
  packages/backend/dist/main.js.map
  packages/backend/dist/tsconfig.build.tsbuildinfo
  packages/backend/package.json
  packages/backend/src/address/address.module.ts
  packages/backend/src/address/address.service.spec.ts
  packages/backend/src/address/address.service.ts
  packages/backend/src/address/dto/create-address.dto.ts
  packages/backend/src/address/dto/update-address.dto.ts
  packages/backend/src/app.module.ts
  packages/backend/src/characteristic/characteristic.controller.spec.ts
  packages/backend/src/characteristic/characteristic.controller.ts
  packages/backend/src/characteristic/characteristic.module.ts
  packages/backend/src/characteristic/characteristic.schema.ts
  packages/backend/src/characteristic/characteristic.service.spec.ts
  packages/backend/src/characteristic/characteristic.service.ts
  packages/backend/src/characteristic/dto/create-characteristic.dto.ts
  packages/backend/src/characteristic/dto/update-characteristic.dto.ts
  packages/backend/src/image/dto/create-image.dto.ts
  packages/backend/src/image/dto/update-image.dto.ts
  packages/backend/src/image/image.module.ts
  packages/backend/src/image/image.service.spec.ts
  packages/backend/src/image/image.service.ts
  packages/backend/src/main.ts
  packages/backend/src/rental-place/dto/create-rental-place.dto.ts
  packages/backend/src/rental-place/dto/update-rental-place.dto.ts
  packages/backend/src/rental-place/rental-place.controller.spec.ts
  packages/backend/src/rental-place/rental-place.controller.ts
  packages/backend/src/rental-place/rental-place.module.ts
  packages/backend/src/rental-place/rental-place.schema.ts
  packages/backend/src/rental-place/rental-place.service.spec.ts
  packages/backend/src/rental-place/rental-place.service.ts
  packages/backend/src/rule/dto/create-rule.dto.ts
  packages/backend/src/rule/dto/update-rule.dto.ts
  packages/backend/src/rule/rule.module.ts
  packages/backend/src/rule/rule.service.spec.ts
  packages/backend/src/rule/rule.service.ts
  packages/backend/src/school/dto/create-school.dto.ts
  packages/backend/src/school/dto/update-school.dto.ts
  packages/backend/src/school/school.controller.spec.ts
  packages/backend/src/school/school.controller.ts
  packages/backend/src/school/school.module.ts
  packages/backend/src/school/school.service.spec.ts
  packages/backend/src/school/school.service.ts
  packages/backend/src/service/dto/create-service.dto.ts
  packages/backend/src/service/dto/update-service.dto.ts
  packages/backend/src/service/service.controller.spec.ts
  packages/backend/src/service/service.controller.ts
  packages/backend/src/service/service.module.ts
  packages/backend/src/service/service.service.spec.ts
  packages/backend/src/service/service.service.ts
  yarn.lock
Labels: enhancement

#23 Alfredo/profile
  packages/frontend/public/images/avatar.png
  packages/frontend/src/components/common/NavBar/UserButton.tsx
  packages/frontend/src/components/common/NavBar/UserMenu.tsx
  packages/frontend/src/pages/profile.tsx
  packages/frontend/src/pages/register.tsx
Labels: enhancement, ready for review
