Repository student-life-project/monorepo, pull requests merged in 2023-03, with the labels that each got.

#46 fix(backend): fixed wrong information parse and moved logic to persist token in webapp
  packages/backend/src/address/address.schema.ts
  packages/backend/src/address/address.service.ts
  packages/backend/src/address/dto/create-address.dto.ts
  packages/backend/src/address/dto/update-address.dto.ts
  packages/backend/src/authz/permissions.guard.ts
  packages/backend/src/main.ts
  packages/backend/src/rental-place/dto/create-rental-place.dto.ts
  packages/backend/src/rental-place/rental-place.command.ts
  packages/backend/src/rental-place/rental-place.controller.ts
  packages/backend/src/rental-place/rental-place.service.ts
  packages/frontend/src/pages/_app.tsx
  packages/frontend/src/pages/profile/publications/post/[[...id]].tsx
  packages/frontend/src/pages/rentals/details/[id].tsx
  packages/frontend/src/services/api.ts
  packages/frontend/src/store/actions/publications.ts
  packages/frontend/src/types/index.ts
  session-temp.txt
Labels: bug

#47 fix(frontend): fix images logic
  packages/backend/src/rental-place/rental-place.controller.ts
  packages/backend/src/user/user.service.ts
  packages/frontend/src/components/publications/Dropzone/Dropzone.tsx
  packages/frontend/src/hooks/useFileReader.ts
Labels: bug, enhancement

#48 fix(backend): removed unneeded spread operator for queries
  packages/backend/src/rental-place/rental-place.controller.ts
  packages/frontend/src/services/api.ts
  packages/frontend/src/store/actions/publications.ts
Labels: bug

#49 fix(frontend): moved logic to handle token in frontend interceptor to app file
  packages/frontend/src/pages/_app.tsx
  packages/frontend/src/pages/profile/publications/post/[[...id]].tsx
  packages/frontend/src/services/api.ts
Labels: bug, enhancement

#50 feat: all get post, and detail post
  packages/frontend/src/components/common/Table.tsx
  packages/frontend/src/components/profile/PostDetails.tsx
  packages/frontend/src/components/publications/PreviewStep4.tsx
  packages/frontend/src/constants/tablesStructure.tsx
  packages/frontend/src/pages/profile/publications/details/[id].tsx
  packages/frontend/src/pages/profile/publications/index.tsx
  packages/frontend/src/pages/profile/publications/post/[[...id]].tsx
  packages/frontend/src/store/actions/publications.ts
  packages/frontend/src/store/reducers/index.ts
  packages/frontend/src/store/reducers/publications.ts
  packages/frontend/src/store/selectors/publications.ts
  packages/frontend/src/types/index.ts
Labels: enhancement

#51 fix(frontend): fixed logic to send images to the backend
  .gitignore
  packages/backend/src/config/multer.config.ts
  packages/backend/src/image/image.schema.ts
  packages/backend/src/image/image.service.ts
  packages/backend/src/rental-place/dto/create-rental-place.dto.ts
  packages/backend/src/rental-place/rental-place.controller.ts
  packages/backend/src/rental-place/rental-place.schema.ts
  packages/backend/src/rental-place/rental-place.service.ts
  packages/frontend/next.config.js
  packages/frontend/src/components/publications/Dropzone/Dropzone.tsx
  packages/frontend/src/components/publications/PreviewStep4.tsx
  packages/frontend/src/pages/profile/publications/post/[[...id]].tsx
  packages/frontend/src/store/actions/publications.ts
Labels: bug, enhancement

#52 fix(frontend): fixed images object where images where extracted to display them in pages
  packages/backend/src/rental-place/rental-place.controller.ts
  packages/backend/src/user/user.service.ts
  packages/frontend/src/pages/index.tsx
  packages/frontend/src/pages/rentals/details/[id].tsx
  packages/frontend/src/pages/rentals/index.tsx
Labels: bug

#53 chore(backend): removed validation causing errors for non admin profiles
  packages/backend/src/rental-place/rental-place.controller.ts
Labels: bug

#59 feat: link profile added
  packages/frontend/src/components/common/Footer.tsx
Labels: enhancement

#61 feat: change publication availability
  packages/frontend/src/components/profile/PostDetails.tsx
  packages/frontend/src/pages/profile/publications/index.tsx
  packages/frontend/src/store/actions/publications.ts
  packages/frontend/src/types/index.ts
  packages/frontend/src/utils/availablePostFormat.ts
Labels: enhancement

#67 feat(frontend): displaying owner information in publication
  packages/frontend/src/pages/rentals/details/[id].tsx
Labels: enhancement

#69 feat(frontend): implemented logic to handle correctly the logout and not require login all the time
  packages/frontend/src/components/common/NavBar/NavBarContainer.tsx
  packages/frontend/src/pages/api/auth/[...auth0].tsx
Labels: enhancement

#70 fix: user update and fetch logic for profile pages
  packages/backend/src/rental-place/rental-place.controller.ts
  packages/backend/src/user/user.controller.ts
  packages/backend/src/user/user.schema.ts
  packages/backend/src/user/user.service.ts
  packages/frontend/src/components/profile/UpdateUser.tsx
  packages/frontend/src/pages/profile/index.tsx
Labels: bug

#73 feat(frontend): improvements for searchbar
  packages/frontend/src/components/common/SearchBar/SearchBar.tsx
  packages/frontend/src/components/common/SearchBar/SearchBarContainer.tsx
  packages/frontend/src/pages/profile/index.tsx
  packages/frontend/src/pages/rentals/index.tsx
Labels: enhancement
